services:
  pandoc:
    image: pandoc/extra:latest
    container_name: pandoc
    restart: unless-stopped
    working_dir: /workspace
    volumes:
      - ../../..:/workspace
      - /:/host:ro
    entrypoint: ["sh", "-c", "while true; do sleep 3600; done"]
