services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:latest-fat
    ports:
      - target: 8080     # Container port
        published: 8080  # Host port
    volumes:
      - type: bind
        source: ./.stirling-pdf/trainingData
        target: /usr/share/tessdata # Required for extra OCR languages
      - type: bind
        source: ./.stirling-pdf/extraConfigs
        target: /configs
      - type: bind
        source: ./.stirling-pdf/customFiles
        target: /customFiles/
      - type: bind
        source: ./.stirling-pdf/logs
        target: /logs/
      - type: bind
        source: ./.stirling-pdf/pipeline
        target: /pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=en_GB
