services:
  vert:
    image: ghcr.io/vert-sh/vert:latest
    container_name: vert
    restart: unless-stopped
    environment:
      - PORT=8080
      - PUB_HOSTNAME=http://localhost:8080
      - PUB_VERTD_URL=http://localhost:8080
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
